package main.repository;

import java.util.List;
import main.entities.AccountInfo;
import main.entities.AccountInfoExample;
import org.apache.ibatis.annotations.Param;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    long countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    int insertSelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 15:11:49 CST 2018
     */
    int updateByExample(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);
}