package main.repository;

import java.util.List;
import main.entities.AccountInfo;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 14:57:54 CST 2018
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Fri Jul 06 14:57:54 CST 2018
     */
    List<AccountInfo> selectAll();
}